name: Thermo CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: Dockerfile
      PROJECT: Application/Application.csproj
      APPSETTINGS: Application/appsettings.json
      REPLACESETTINGS: Application/Deployment/appsettings.Production.json
      TAG: interthermo
    steps:
     - uses: actions/checkout@v2
     - name: files-ls
       uses: sigyl-actions/files-ls@v0.0.1
       with:
        folder: "/"      
     - 
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["${{env.REPLACESETTINGS}}"]'
      env:
        RABBIT_USER : ${{secrets.RABBIT_USER}}
        RABBIT_PASSWORD : ${{secrets.RABBIT_PASSWORD}}
        INFLUXDB_TOKEN : ${{secrets.INFLUXDB_TOKEN}}
     - 
      name: Replace Appsettings
      run: cp ${{env.REPLACESETTINGS}} ${{env.APPSETTINGS}}
     - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
     - 
      name: Restore dependencies
      run: dotnet restore
     - 
      name: Build
      run: dotnet build --no-restore
     - 
      name: Publish
      run: dotnet publish -c Release -o ./app
     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
        registry: ${{secrets.DOCKER_HOST}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}      
     - name: Build and push Docker images
       uses: docker/build-push-action@v5.1.0
       with:
            context: ./
            file: Dockerfile
            push: true
            tags: |
              ${{secrets.DOCKER_HOST}}/${{env.TAG}}
  deploy:
    needs: build-publish
    runs-on: self-hosted
    env:
      TAG: interthermo
    steps:
     - name: SSH Command
       uses: nekiro/ssh-job@v1.0.5
       with:
        command: sudo docker pull ${{secrets.DOCKER_HOST}}/${{env.TAG}}; sudo docker stop ${{env.TAG}}; sudo docker rm ${{env.TAG}}; sudo docker run --name ${{env.TAG}} --restart=unless-stopped --net inter_network -m=500m --dns=10.0.0.33 -d ${{secrets.DOCKER_HOST}}/${{env.TAG}}; 
        host: ${{secrets.HOST}}
        user: ${{secrets.CENTURION_USERNAME}}
        password: ${{secrets.CENTURION_PASSWORD}}
